### PR TITLE
Add husky and commit lint

### PR DESCRIPTION
**Pull request by vedantnn71**
Husky and commitlint can significantly improve quality of commits and code pushed with errors.

Before every commit, husky will lint the code to verify whether everything is fine or not, and commitlint will verify whether commits are consistent or not.

### CODE REVIEW

**Comment by subhoghoshX** [comment]
Looks good. I don't think you need to specify `rules` in `.commitlintrc.json`, the default ones we get by extending `@commitlint/config-conventional` are good enough.

And I was wondering what's the purpose of this `.yarnrc.yml` file.

**Comment by vedantnn71** [comment]
> Looks good. I don't think you need to specify `rules` in `.commitlintrc.json`, the default ones we get by extending `@commitlint/config-conventional` are good enough.

I saw that you were using _misc_ quite a lot and that is not present in the @commitlint/config-conventional.
 
> And I was wondering what's the purpose of this `.yarnrc.yml` file.

Commitlint does not seem to work out of the box with yarn, so adding `nodeLinker: node-modules` in the yarnrc can resolve the issue.

**Comment by subhoghoshX** [comment]
Haha dude I used `misc` only once or twice. I sometimes invent my own rules on the go like `ui`, `misc`, `dx` etc. You can remove those, that'll force me to be a little consistent from now on I guess.

> Commitlint does not seem to work out of the box with yarn, so adding nodeLinker: node-modules in the yarnrc can resolve the issue.

It seems to work for me without it. No issues keep it. Maybe it depends on the environment.

**Comment by subhoghoshX** [comment]
Plus just noticed, you don't even have `misc` in the rules :laughing:

**Comment by vedantnn71** [comment]
> Plus just noticed, you don't even have `misc` in the rules laughing

oopps, I forgot to add them, nvm I removed all the custom rules haha

**Pull request merged**
