### PR TITLE
feat: theme persitence is now enabled using zustand persist

### PR DESCRIPTION
**Pull request by Karthik-315**
Added persistence to the color theme using zustand's persist middleware.

Relevant Issue: #57

### CODE REVIEW

**Comment by Karthik-315** [comment]
> Thanks, @Karthik-315. Could you explain what you did in `index.tsx` and why?

I used `useEffect` and conditional rendering to ensure that client hydration happens only after the `isDark` state is set from `localStorage` from the `persist` function. 
    
 Else Next JS throws an error due to difference in code b/w client and server (since there is no localStorage in the server, there was a difference in the value of `isDark` state b/w client and server).

**Comment by subhoghoshX** [comment]
Got it. Thanks for the explanation. The only issue with your implementation is that it completely turns off Next's static site rendering. I was looking at zustand persist middleware and couldn't find a better way.

**Comment by jalezi** [comment]
I'm pretty sure that there is no need to wrap everything in another div and append class "dark".

code from [offical page](https://tailwindcss.com/docs/dark-mode) ⬇️ 
```html
<!-- Dark mode not enabled -->
<html>
<body>
  <!-- Will be white -->
  <div class="bg-white dark:bg-black">
    <!-- ... -->
  </div>
</body>
</html>

<!-- Dark mode enabled -->
<html class="dark">
<body>
  <!-- Will be black -->
  <div class="bg-white dark:bg-black">
    <!-- ... -->
  </div>
</body>
</html>
```

**Comment by Karthik-315** [comment]
> Got it. Thanks for the explanation. The only issue with your implementation is that it completely turns off Next's static site rendering. I was looking at zustand persist middleware and couldn't find a better way.

Yeah, I guess it just works that way. Even if we resort to the native `localStorage` we may have to use `useEffect` (because of the `window` object) and I guess that too would make things dynamic on the client side. My guess is that (correct me if I am wrong) to implement persistence, we may have to go around static rendering. Let me know.

**Comment by jalezi** [comment]
I will replace outer div with fragment and use

```javascript
// for tailwind css, need the change the root
export const applyThemePreference = (theme) => {
  const { THEME_DARK, THEME_LIGHT } = THEME_TYPES;
  const root = window.document.documentElement;
  const isDark = theme === THEME_DARK;
  root.classList.remove(isDark ? THEME_LIGHT : THEME_DARK);
  root.classList.add(theme);
};
```
in custom hook.

**Comment by Karthik-315** [comment]
> You can solve it using a buffer state like this:
> 
> ```js
> const [isDarkBuffer, setIsDarkBuffer] = useState(false);
> useEffect(() => setIsDarkBuffer(isDark), [isDark]);
> 
> return (
>     <div className={`${isDarkBuffer ? "dark" : ""}`}>
> ...
> ```
> 
> But then there'll be a flicker during the initial loading. I'm not sure what the best solution would be without using a separate package.

I tried this before as well, as you said if the preferred theme is dark, then the app first renders in Light mode and switches to dark mode upon the second render. The flicker is why I switched to the current approach I implemented.

**Comment by subhoghoshX** [comment]
> I will replace outer div with fragment and use
> 
> ```js
> // for tailwind css, need the change the root
> export const applyThemePreference = (theme) => {
>   const { THEME_DARK, THEME_LIGHT } = THEME_TYPES;
>   const root = window.document.documentElement;
>   const isDark = theme === THEME_DARK;
>   root.classList.remove(isDark ? THEME_LIGHT : THEME_DARK);
>   root.classList.add(theme);
> };
> ```
> 
> in custom hook.

Yeah, I read the article. But does it really solve the flickering issue during the initial load, I don't think so.

**Comment by jalezi** [comment]
Not sure about flickering. I tried but not really paying attention and then I s.... up when trying to implement prefers dark 😃 
I can do it again, create PR, and we will see

**Comment by subhoghoshX** [comment]
The library `next-themes` can solve the issue and also the flickering, but let me see if I can do it the vanilla way first.

**Comment by jalezi** [comment]
> The library `next-themes` can solve the issue and also the flickering, but let me see if I can do it the vanilla way first.

or with cookie

**Comment by subhoghoshX** [comment]
> or with cookie

Nice. Thought of that, but that'd require us to use `getServerSideProps` and render the page on every request. Not sure.

**Comment by jalezi** [comment]
> > or with cookie
> 
> Nice. Thought of that, but that'd require us to use `getServerSideProps` and render the page on every request. Not sure.

or `getInitialProps`

**Comment by subhoghoshX** [comment]
> or `getInitialProps` in `_app.tsx`.

Haha, that also does server-side rendering, no? If `next-themes` can do it on the client side without flickering, then we can too. We just have to figure it out. And I think I've found a solution.

**Comment by subhoghoshX** [comment]
@Karthik-315 the solution I found is Next Script. Using the <Script /> component you can inject some js into the head of the document, which will always run before anything, even before the UI is rendered.

In `index.tsx` you can do this.

```js
<Script
  dangerouslySetInnerHTML={{
    __html: `
    const isDark = localStorage.getItem('isDark');
    if(isDark === 'true') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  `,
  }}
  strategy="beforeInteractive"
/>

// This only executes once during the initial loading
```

And in `ButtonGroup.tsx` you can have a click handler with something like this:

```js
function toggleDark() {
  if (isDark === "true") {
    document.documentElement.classList.remove("dark");
    localStorage.setItem("isDark", "false");
  } else {
    document.documentElement.classList.add("dark");
    localStorage.setItem("isDark", "true");
  }
}

// Here document.documentElement is the root `html` element.
// The function toggles the `dark` class and also the localStorage value 
// which is used the next time the page is loaded.
```

The good thing about this implementation is that we can get rid of the dark store and the actions completely. Do you guys like it? I don't see any issues with this approach so far. Let me know if you have some other ideas.

**Comment by Karthik-315** [comment]
> @Karthik-315 the solution I found is Next Script. Using the <Script /> component you can inject some js into the head of the document, which will always run before anything, even before the UI is rendered.
> 
> In `index.tsx` you can do this.
> 
> ```js
> <Script
>   dangerouslySetInnerHTML={{
>     __html: `
>     const isDark = localStorage.getItem('isDark');
>     if(isDark === 'true') {
>       document.documentElement.classList.add('dark');
>     } else {
>       document.documentElement.classList.remove('dark');
>     }
>   `,
>   }}
>   strategy="beforeInteractive"
> />
> 
> // This only executes once during the initial loading
> ```
> 
> And in `ButtonGroup.tsx` you can have a click handler with something like this:
> 
> ```js
> function toggleDark() {
>   if (isDark === "true") {
>     document.documentElement.classList.remove("dark");
>     localStorage.setItem("isDark", "false");
>   } else {
>     document.documentElement.classList.add("dark");
>     localStorage.setItem("isDark", "true");
>   }
> }
> 
> // Here document.documentElement is the root `html` element.
> // The function toggles the `dark` class and also the localStorage value 
> // which is used the next time the page is loaded.
> ```
> 
> The good thing about this implementation is that we can get rid of the dark store and the actions completely. Do you guys like it? I don't see any issues with this approach so far. Let me know if you have some other ideas.

Looks good to me. Yeah, and this means ditching state variables, the `persist` function, and store for the theme and resorting to the native approach along with the `<Script />` tag. 

I don't know zustand much, so not quite sure if there is any added advantage of  `persist` over this. But I am good with this implementation too. Let me know I'll do this and submit a PR.

**Comment by subhoghoshX** [comment]
Just now I was looking at the source code of `next-themes` they're also using a script tag [there](https://github.com/pacocoursey/next-themes/blob/main/src/index.tsx#L265). Everything is a native approach under the hood anyway hehe.

Feel free to go ahead. Just revert the changes first with `git revert HEAD` and then implement it, that might be easier for you I guess. And delete unnecessary store files and lines.

**Comment by Karthik-315** [comment]
@subhoghoshX I've submitted a PR with the changes, but it says above there is a conflict in the `ButtonGroup.tsx` file. Would it be easy for you to fix and merge this file? Else, I can submit another PR with the updated file, resolving conflicts. Let me know.

**Comment by subhoghoshX** [comment]
Huh, looks like you forgot to update your branch first @Karthik-315.

**Comment by subhoghoshX** [comment]
> @subhoghoshX I've submitted a PR with the changes, but it says above there is a conflict in the `ButtonGroup.tsx` file. Would it be easy for you to fix and merge this file? Else, I can submit another PR with the updated file, resolving conflicts. Let me know.

Let me see.

**Comment by Karthik-315** [comment]
> Huh, looks like you forgot to update your branch first @Karthik-315.

Yeah, I totally forgot about that and went all in on pushing the changes hehe.

**Comment by subhoghoshX** [comment]
> Yeah, I totally forgot about that and went all in on pushing the changes hehe. Let me know if you need me to update the branch and push again.

No worries, I already resolved the conflict :)

**Pull request merged**
