### PR TITLE
Add gif to readme

### PR DESCRIPTION
**Pull request by Karthik-315**
Added a GIF of the working of the app to README. 

[Link to file](https://github.com/Karthik-315/laureate/blob/add-gif-to-readme/README.md)

### CODE REVIEW

**Comment by subhoghoshX** [comment]
Thanks @Karthik-315, looks good. Did you just recorded the video and turned it into a GIF?

**Comment by subhoghoshX** [comment]
There's a few things I just noticed.
1. It doesn't look good when using small tweets; I should probably set a min-width on the inner card.
2. The red color is horrible :laughing:; perhaps I should just remove it.
3. Lastly, could you showcase a few more features? Like resizing the card, changing the font to something else, Comic Sans maybe :rofl: and that you can change values by dragging over the labels too.

**Comment by Karthik-315** [comment]
Cool dude. I used Gifcam to record the gif. I kept it minimalistic to avoid huge GIF size, but sure, I'll showcase more features as you'd mentioned. 

I thought the red gradient looks good though 😝. I'll use another gradient for the recording and a longer tweet to showcase. Is there any particular gradient you'd like to be dosplayed?

**Comment by subhoghoshX** [comment]
You can use any other gradient.

> I thought the red gradient looks good though :stuck_out_tongue_closed_eyes:

Interesting. I'll keep it then. I might reduce the redness a little.

**Comment by Karthik-315** [comment]
Added a detailed GIF showcasing more features. Recorded at 10 FPS to limit the file size. Let me know what you think of it.

**Review by subhoghoshX — APPROVED** [review]

**Pull request merged**
