### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by Rounak-28**
Screenshot

Screenshot 2022-10-01 100037

### CODE REVIEW

**Comment by Rounak-28** [comment]
@subhoghoshX please check

**Comment by subhoghoshX** [comment]
Thanks for working on it. Look like you didn't sync your branch with upstream. Please do it. That way I'll be able to see the proper preview.

**Comment by Rounak-28** [comment]
@subhoghoshX Can you please check now?

**Comment by subhoghoshX** [comment]
I don't think we need `next-themes`. You could've just done it with a normal state.

**Comment by Rounak-28** [comment]
@subhoghoshX  Okay will do that.
btw should I open a new PR and close this?

**Comment by subhoghoshX** [comment]
No, leave it like that, I don't want your efforts to go in vain.

Remove the dark icon and laureate-logo image. I'll fix them after merging the PR.

And I saw that you used npm which changed the yarn lock file and also added a new `package-lock.json` file. Fix those.

**Comment by Rounak-28** [comment]
@subhoghoshX check now 🙂

**Comment by subhoghoshX** [comment]
There are merge conflicts. Could you fix it?

**Comment by Rounak-28** [comment]
@subhoghoshX  I guess conflicts are resolved, please check

**Comment by subhoghoshX** [comment]
Not really. I think you just discarded all the changes. You need keep the changes that you're pulled.

**Comment by subhoghoshX** [comment]
Closing this as the feature is already implemented.

**Pull request closed without merging**
