### PR TITLE
Feat: ✨ Check icon when file is downloaded/copied

### LINKED ISSUE #32: [FEAT] Trigger a message when file is copied/downloaded
## Problem

Currently, whenever user clicks on save or copy button, nothing happens on the completion of the task. For save button, you know if it worked or not as you'll see a new file downloading, but for copy button, you've no idea even if it's working or not!

## Solution
We can add a success message (maybe in the form of a toast) whenever user downloads or copies an image. Maybe we can use a package for that such as [React-Toastify](https://www.npmjs.com/package/react-toastify) for that.

Also, I'd love to work on this issue!

### PR DESCRIPTION
**Pull request by jalezi**
When img is copied or downloaded icon check will appear for 1 second instead of save/copy icon.

Introduces 5 new components, which at the moment still resides in one file `ExportButton.tsx`. 3 components for svgs and 2 for each action (save/copy) and `useIcon()` hook.
Probably it would be better to move new components somewhere else at least SVG components.

FIX #32

### CODE REVIEW

**Comment by jalezi** [comment]
@subhoghoshX At the moment I wrapped save/copy in `try...catch`. Should we notify if something goes wrong or just do nothing and I remove `try...catch`.

**Comment by jalezi** [comment]
@subhoghoshX let's wait if #56 will be merged due to https://github.com/subhoghoshX/laureate/issues/32#issuecomment-1268602443.

In case of using `react-hot-toast` we can change icon on click and notify when error/done.

**Comment by subhoghoshX** [comment]
Nah, keep going, the toast looks ugly anyway. Btw, just noticed, you're supposed to add a simple icon. It looks you changed too many things.

**Comment by jalezi** [comment]
> ... Btw, just noticed, you're supposed to add a simple icon. It looks you changed too many things.

@subhoghoshX I just broke one large component into smaller components. A lot of `svg` bothers me. If asked, I would move all "svg" someone else. I kinda like them as [components](https://react-svgr.com/docs/next/), especially if there are many. 😄 But this is just my preference.

I will mark PR for review maybe you will change your mind 😄. Otherwise I will change.

**Comment by subhoghoshX** [comment]
Installed heroicons for you and replaced the SVGs. Now you can use that instead.

**Comment by jalezi** [comment]
I'll check tomorrow.

**Comment by subhoghoshX** [comment]
I don't think it's worth having separate save and copy components anymore.

**Comment by jalezi** [comment]
btw @subhoghoshX do you know https://poet.so/?

**Comment by subhoghoshX** [comment]
> btw @subhoghoshX do you know https://poet.so/?

Yes.

**Review by subhoghoshX — APPROVED** [review]

**Pull request merged**
