### PR TITLE
feat: Add missing meta tags

### PR DESCRIPTION
**Pull request by devXprite**

### CODE REVIEW

**Comment by subhoghoshX** [comment]
Looks good, how about adding a preview image?

**Comment by subhoghoshX** [comment]
Looks good, thank you. How about adding a preview image?

**Comment by devXprite** [comment]
> Looks good, thank you. How about adding a preview image?

Hii @subhoghoshX I add [this](https://github.com/subhoghoshX/laureate/blob/d7e2d2bc20a8abe1dccfeca7700c2ec44f56aed3/public/preview.png) as a preview image for Twitter & Open Graph.

**Review by subhoghoshX — APPROVED** [review]

**Comment by subhoghoshX** [comment]
Looks good, thank you so much @devXprite.

**Pull request merged**
